<a href="https://colab.research.google.com/github/pellurupooja/Tensorflow-AND-OR-Gate/blob/main/Tf_AND_OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

Creating dataset for an And Gate

In [ ]:
x = np.array([[0,0], [0,1], [1,0], [1,1]], "uint8") #input
y = np.array([[0], [0], [0], [1]], "uint8") #output

Creating a sequential model using tensorflow

In [ ]:
model = Sequential()
model.add(Dense(units = 1, activation = 'sigmoid', input_dim = 2)) #only one output
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy']) 
# model.summary()

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


3 parameters to find (w0,w1,w2)


In [ ]:
model.fit(x, y, epochs = 750)  

Epoch 1/750
1/1 [==============================] - 1s 867ms/step - loss: 0.7374 - accuracy: 0.7500
Epoch 2/750
1/1 [==============================] - 0s 8ms/step - loss: 0.7370 - accuracy: 0.7500
Epoch 3/750
1/1 [==============================] - 0s 6ms/step - loss: 0.7366 - accuracy: 0.7500
Epoch 4/750
1/1 [==============================] - 0s 8ms/step - loss: 0.7361 - accuracy: 0.7500
Epoch 5/750
1/1 [==============================] - 0s 10ms/step - loss: 0.7357 - accuracy: 0.7500
Epoch 6/750
1/1 [==============================] - 0s 7ms/step - loss: 0.7353 - accuracy: 0.7500
Epoch 7/750
1/1 [==============================] - 0s 11ms/step - loss: 0.7348 - accuracy: 0.7500
Epoch 8/750
1/1 [==============================] - 0s 9ms/step - loss: 0.7344 - accuracy: 0.7500
Epoch 9/750
1/1 [==============================] - 0s 9ms/step - loss: 0.7340 - accuracy: 0.7500
Epoch 10/750
1/1 [==============================] - 0s 6ms/step - loss: 0.7336 - accuracy: 0.7500
Epoch 11/750
1/1 [=======

In [ ]:
print(model.layers[0].get_weights())

[array([[0.5374165],
       [0.3244282]], dtype=float32), array([-0.6681946], dtype=float32)]


In [ ]:
model.predict(x)

array([[0.33890122],
       [0.41489488],
       [0.467352  ],
       [0.5482618 ]], dtype=float32)

CREATING DATABASE FOR A XOR GATE

In [ ]:
x=[[0,0], [0,1], [1,0], [1,1]]
y = [[0], [1], [1], [0]]

In [ ]:
xor = Sequential()
xor.add(Dense(2, input_dim = 2, activation='sigmoid'))
xor.add(Dense(1, activation='sigmoid'))
xor.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
xor.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
xor.fit(x, y , epochs = 1000)

Epoch 1/1000
1/1 [==============================] - 0s 493ms/step - loss: 0.7617 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7612 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.7607 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.7602 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7597 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7593 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.7588 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.7583 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.7578 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7573 - accuracy: 0.5000
Epoch 11/1000
1/1

In [ ]:
xor.get_weights()

[array([[-1.4892671 ,  0.6284218 ],
        [ 0.9282697 , -0.78604776]], dtype=float32),
 array([-0.45434883, -0.44666395], dtype=float32),
 array([[0.29170457],
        [0.63639075]], dtype=float32),
 array([-0.33140394], dtype=float32)]

In [ ]:
xor.predict(x)

array([[0.5075403 ],
       [0.49800372],
       [0.51303846],
       [0.49276233]], dtype=float32)